#define CHALK_LEMON_RPN_OPERATOR_ASSIGN                  1
#define CHALK_LEMON_RPN_OPERATOR_ASSIGN_DYNAMIC          2
#define CHALK_LEMON_RPN_OPERATOR_SHL                     3
#define CHALK_LEMON_RPN_OPERATOR_SHL2                    4
#define CHALK_LEMON_RPN_OPERATOR_SHR                     5
#define CHALK_LEMON_RPN_OPERATOR_SHR2                    6
#define CHALK_LEMON_RPN_OPERATOR_OR                      7
#define CHALK_LEMON_RPN_OPERATOR_OR2                     8
#define CHALK_LEMON_RPN_OPERATOR_XOR                     9
#define CHALK_LEMON_RPN_OPERATOR_XOR2                   10
#define CHALK_LEMON_RPN_OPERATOR_AND                    11
#define CHALK_LEMON_RPN_OPERATOR_AND2                   12
#define CHALK_LEMON_RPN_OPERATOR_LEQ                    13
#define CHALK_LEMON_RPN_OPERATOR_LEQ2                   14
#define CHALK_LEMON_RPN_OPERATOR_GEQ                    15
#define CHALK_LEMON_RPN_OPERATOR_GEQ2                   16
#define CHALK_LEMON_RPN_OPERATOR_LOW                    17
#define CHALK_LEMON_RPN_OPERATOR_LOW2                   18
#define CHALK_LEMON_RPN_OPERATOR_GRE                    19
#define CHALK_LEMON_RPN_OPERATOR_GRE2                   20
#define CHALK_LEMON_RPN_OPERATOR_EQU                    21
#define CHALK_LEMON_RPN_OPERATOR_EQU2                   22
#define CHALK_LEMON_RPN_OPERATOR_NEQ                    23
#define CHALK_LEMON_RPN_OPERATOR_NEQ2                   24
#define CHALK_LEMON_RPN_OPERATOR_ABS                    25
#define CHALK_LEMON_RPN_OPERATOR_PLUS                   26
#define CHALK_LEMON_RPN_OPERATOR_PLUS2                  27
#define CHALK_LEMON_RPN_OPERATOR_MINUS                  28
#define CHALK_LEMON_RPN_OPERATOR_MINUS2                 29
#define CHALK_LEMON_RPN_OPERATOR_DIVIDE                 30
#define CHALK_LEMON_RPN_OPERATOR_DIVIDE2                31
#define CHALK_LEMON_RPN_OPERATOR_TIMES                  32
#define CHALK_LEMON_RPN_OPERATOR_TIMES2                 33
#define CHALK_LEMON_RPN_INDEX_RANGE_JOKER               34
#define CHALK_LEMON_RPN_OPERATOR_POW                    35
#define CHALK_LEMON_RPN_OPERATOR_POW2                   36
#define CHALK_LEMON_RPN_OPERATOR_NOT                    37
#define CHALK_LEMON_RPN_OPERATOR_NOT2                   38
#define CHALK_LEMON_RPN_OPERATOR_MINUS_UNARY            39
#define CHALK_LEMON_RPN_OPERATOR_SQRT                   40
#define CHALK_LEMON_RPN_OPERATOR_SQRT2                  41
#define CHALK_LEMON_RPN_OPERATOR_CBRT                   42
#define CHALK_LEMON_RPN_OPERATOR_CBRT2                  43
#define CHALK_LEMON_RPN_OPERATOR_FACTORIAL              44
#define CHALK_LEMON_RPN_OPERATOR_FACTORIAL2             45
#define CHALK_LEMON_RPN_OPERATOR_UNCERTAINTY            46
#define CHALK_LEMON_RPN_OPERATOR_DEGREE                 47
#define CHALK_LEMON_RPN_OPERATOR_DEGREE2                48
#define CHALK_LEMON_RPN_ENUMERATION_SEPARATOR           49
#define CHALK_LEMON_RPN_OPERATOR_SUBSCRIPT              50
#define CHALK_LEMON_RPN_IF                              51
#define CHALK_LEMON_RPN_THEN                            52
#define CHALK_LEMON_RPN_ELSE                            53
#define CHALK_LEMON_RPN_QUESTION                        54
#define CHALK_LEMON_RPN_ALTERNATE                       55
#define CHALK_LEMON_RPN_INTEGER_POSITIVE                56
#define CHALK_LEMON_RPN_INDEX_RANGE_OPERATOR            57
#define CHALK_LEMON_RPN_REAL_POSITIVE                   58
#define CHALK_LEMON_RPN_INTEGER_PER_FRACTION            59
#define CHALK_LEMON_RPN_REAL_PER_FRACTION               60
#define CHALK_LEMON_RPN_STRING_QUOTED                   61
#define CHALK_LEMON_RPN_INTERVAL_LEFT_DELIMITER         62
#define CHALK_LEMON_RPN_INTERVAL_ITEM_SEPARATOR         63
#define CHALK_LEMON_RPN_INTERVAL_RIGHT_DELIMITER        64
#define CHALK_LEMON_RPN_IDENTIFIER                      65
#define CHALK_LEMON_RPN_PARENTHESIS_LEFT                66
#define CHALK_LEMON_RPN_PARENTHESIS_RIGHT               67
#define CHALK_LEMON_RPN_OPERATOR_MINUS_SQRT             68
#define CHALK_LEMON_RPN_OPERATOR_MINUS_SQRT2            69
#define CHALK_LEMON_RPN_OPERATOR_MINUS_CBRT             70
#define CHALK_LEMON_RPN_OPERATOR_MINUS_CBRT2            71
#define CHALK_LEMON_RPN_LIST_LEFT_DELIMITER             72
#define CHALK_LEMON_RPN_LIST_RIGHT_DELIMITER            73
