#define CHALK_LEMON_OPERATOR_ASSIGN                  1
#define CHALK_LEMON_OPERATOR_ASSIGN_DYNAMIC          2
#define CHALK_LEMON_OPERATOR_SHL                     3
#define CHALK_LEMON_OPERATOR_SHL2                    4
#define CHALK_LEMON_OPERATOR_SHR                     5
#define CHALK_LEMON_OPERATOR_SHR2                    6
#define CHALK_LEMON_OPERATOR_OR                      7
#define CHALK_LEMON_OPERATOR_OR2                     8
#define CHALK_LEMON_OPERATOR_XOR                     9
#define CHALK_LEMON_OPERATOR_XOR2                   10
#define CHALK_LEMON_OPERATOR_AND                    11
#define CHALK_LEMON_OPERATOR_AND2                   12
#define CHALK_LEMON_OPERATOR_LEQ                    13
#define CHALK_LEMON_OPERATOR_LEQ2                   14
#define CHALK_LEMON_OPERATOR_GEQ                    15
#define CHALK_LEMON_OPERATOR_GEQ2                   16
#define CHALK_LEMON_OPERATOR_LOW                    17
#define CHALK_LEMON_OPERATOR_LOW2                   18
#define CHALK_LEMON_OPERATOR_GRE                    19
#define CHALK_LEMON_OPERATOR_GRE2                   20
#define CHALK_LEMON_OPERATOR_EQU                    21
#define CHALK_LEMON_OPERATOR_EQU2                   22
#define CHALK_LEMON_OPERATOR_NEQ                    23
#define CHALK_LEMON_OPERATOR_NEQ2                   24
#define CHALK_LEMON_OPERATOR_ABS                    25
#define CHALK_LEMON_OPERATOR_PLUS                   26
#define CHALK_LEMON_OPERATOR_PLUS2                  27
#define CHALK_LEMON_OPERATOR_MINUS                  28
#define CHALK_LEMON_OPERATOR_MINUS2                 29
#define CHALK_LEMON_OPERATOR_DIVIDE                 30
#define CHALK_LEMON_OPERATOR_DIVIDE2                31
#define CHALK_LEMON_OPERATOR_TIMES                  32
#define CHALK_LEMON_OPERATOR_TIMES2                 33
#define CHALK_LEMON_INDEX_RANGE_JOKER               34
#define CHALK_LEMON_OPERATOR_POW                    35
#define CHALK_LEMON_OPERATOR_POW2                   36
#define CHALK_LEMON_OPERATOR_NOT                    37
#define CHALK_LEMON_OPERATOR_NOT2                   38
#define CHALK_LEMON_OPERATOR_MINUS_UNARY            39
#define CHALK_LEMON_OPERATOR_SQRT                   40
#define CHALK_LEMON_OPERATOR_SQRT2                  41
#define CHALK_LEMON_OPERATOR_CBRT                   42
#define CHALK_LEMON_OPERATOR_CBRT2                  43
#define CHALK_LEMON_OPERATOR_MUL_SQRT               44
#define CHALK_LEMON_OPERATOR_MUL_SQRT2              45
#define CHALK_LEMON_OPERATOR_MUL_CBRT               46
#define CHALK_LEMON_OPERATOR_MUL_CBRT2              47
#define CHALK_LEMON_OPERATOR_FACTORIAL              48
#define CHALK_LEMON_OPERATOR_FACTORIAL2             49
#define CHALK_LEMON_OPERATOR_UNCERTAINTY            50
#define CHALK_LEMON_OPERATOR_DEGREE                 51
#define CHALK_LEMON_OPERATOR_DEGREE2                52
#define CHALK_LEMON_ENUMERATION_SEPARATOR           53
#define CHALK_LEMON_OPERATOR_SUBSCRIPT              54
#define CHALK_LEMON_IF                              55
#define CHALK_LEMON_THEN                            56
#define CHALK_LEMON_ELSE                            57
#define CHALK_LEMON_QUESTION                        58
#define CHALK_LEMON_ALTERNATE                       59
#define CHALK_LEMON_INTEGER_POSITIVE                60
#define CHALK_LEMON_INDEX_RANGE_OPERATOR            61
#define CHALK_LEMON_REAL_POSITIVE                   62
#define CHALK_LEMON_INTEGER_PER_FRACTION            63
#define CHALK_LEMON_REAL_PER_FRACTION               64
#define CHALK_LEMON_STRING_QUOTED                   65
#define CHALK_LEMON_INTERVAL_LEFT_DELIMITER         66
#define CHALK_LEMON_INTERVAL_ITEM_SEPARATOR         67
#define CHALK_LEMON_INTERVAL_RIGHT_DELIMITER        68
#define CHALK_LEMON_IDENTIFIER                      69
#define CHALK_LEMON_PARENTHESIS_LEFT                70
#define CHALK_LEMON_PARENTHESIS_RIGHT               71
#define CHALK_LEMON_LIST_LEFT_DELIMITER             72
#define CHALK_LEMON_LIST_RIGHT_DELIMITER            73
